create table public."ChatMessages" (
  chat_message_id bigint generated by default as identity not null,
  chat_connection_id uuid not null,
  message text not null,
  sender_id uuid null,
  receiver_id uuid null,
  is_read boolean not null default false,
  created_at timestamp with time zone not null default now(),
  constraint ChatMessages_pkey primary key (chat_message_id),
  constraint ChatMessages_chat_connection_id_fkey foreign key (chat_connection_id) references public."ChatConnections" (chat_connection_id) on update cascade on delete cascade,
  constraint ChatMessages_sender_id_fkey foreign key (sender_id) references auth.users (id) on update cascade on delete cascade,
  constraint ChatMessages_receiver_id_fkey foreign key (receiver_id) references auth.users (id) on update cascade on delete cascade
) tablespace pg_default;