create table
public."Feedback" (
    feedback_id bigint generated by default as identity not null,
    farmer_id uuid not null,
    technician_id uuid not null,
    feedback_message text not null,
    ratings smallint not null,
    created_at timestamp with time zone not null default now(),
    constraint Feedback_pkey primary key (feedback_id),
    constraint Feedback_farmer_id_fkey foreign key (farmer_id) references auth.users (id) on update cascade on delete cascade,
    constraint Feedback_technician_id_fkey foreign key (technician_id) references auth.users (id) on update cascade on delete cascade
) tablespace pg_default;