create table public."Feedback" (
  feedback_id bigint generated by default as identity not null,
  chat_connection_id uuid not null,
  feedback_message text not null,
  ratings smallint not null,
  created_at timestamp with time zone not null default now(),
  constraint Feedback_pkey primary key (feedback_id),
  constraint Feedback_chat_connection_id_fkey foreign key (chat_connection_id) references "ChatConnections" (chat_connection_id) on update cascade on delete cascade
) tablespace pg_default;