create table
  public."Feedback" (
    feedback_id bigint generated by default as identity not null,
    chat_message_id bigint not null,
    feedback_message text not null,
    ratings smallint not null,
    created_at timestamp with time zone not null default now(),
    constraint Feedback_pkey primary key (feedback_id),
    constraint Feedback_chat_message_id_fkey foreign key (chat_message_id) references "ChatMessages" (chat_message_id) on update cascade on delete cascade
  ) tablespace pg_default;