create table public."PremadePrompts" (
    prompt_id bigint generated by default as identity not null,
    prompt_message text not null,
    category text not null,
    prompt_order integer not null,
    created_at timestamp with time zone not null default now(),
    constraint PremadePrompts_pkey primary key (prompt_id),
    constraint PremadePrompts_category_fkey foreign key (category) references "PromptCategory" (category_name) on update cascade on delete cascade
) tablespace pg_default;