create table
public."PremadePrompts" (
    prompt_id bigint generated by default as identity not null,
    prompt_message text not null,
    prompt_order integer not null,
    created_at timestamp with time zone not null default now(),
    constraint PremadePrompts_pkey primary key (prompt_id)
) tablespace pg_default;