create table
public."ReadingLists" (
    list_id bigint generated by default as identity not null,
    file_url text not null,
    list_order integer not null,
    created_at timestamp with time zone not null default now(),
    constraint ReadingLists_pkey primary key (list_id)
) tablespace pg_default;