create table
public."SuggestedLinks" (
    link_id bigint generated by default as identity not null,
    link_name text not null,
    link_url text not null,
    link_order integer not null,
    created_at timestamp with time zone not null default now(),
    constraint SuggestedLinks_pkey primary key (link_id)
) tablespace pg_default;