  create table
    public."TechnicianUsers" (
      user_id bigint generated by default as identity not null,
      auth_user_id text null,
      first_name text not null,
      last_name text not null,
      middle_name text null,
      mobile_number text not null,
      birth_date text not null,
      address text not null,
      email text not null,
      password text not null,
      account_status text not null default 'pending'::text,
      license_number text null,
      specialization text not null,
      created_at timestamp with time zone not null default now(),
      constraint users_pkey primary key (user_id),
      constraint users_email_key unique (email)
    ) tablespace pg_default;