create table
  public."TechnicianUsers" (
    user_id bigint generated by default as identity not null,
    auth_user_id text null,
    first_name text not null,
    last_name text not null,
    middle_name text null,
    birth_date text not null,
    location text not null,
    specialization text not null,
    email text not null,
    password text not null,
    account_status text not null default 'pending'::text,
    created_at timestamp with time zone not null default now(),
    constraint Users_pkey primary key (user_id),
    constraint Users_email_key unique (email)
  ) tablespace pg_default;